from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from ..config import load_yaml
from ..features.registry import FeatureRegistry
from ..rules.dsl import engine_json, rule_to_expression
from ..schemas import (
    ActionType,
    BacktestMetrics,
    GovernanceDecision,
    StrategyCandidate,
    StrategyRequest,
    StrategyStatus,
)


@dataclass
class StrategyGovernanceWorkflow:
    """Evaluates a strategy against deployment, compliance, and audit gates.

    The workflow intentionally stops at ``PENDING_REVIEW``. No strategy generated by the
    prototype is allowed to move directly to ONLINE. This mirrors the risk-control design
    principle of simulation -> dual review -> approval -> controlled release.
    """

    governance_path: str | Path
    feature_registry: FeatureRegistry

    def __post_init__(self) -> None:
        self.config: dict[str, Any] = load_yaml(self.governance_path)

    def _transition_allowed(self, current: StrategyStatus, target: StrategyStatus) -> bool:
        transitions = self.config.get("status_transitions", {})
        return target.value in transitions.get(current.value, [])

    def review(
        self,
        strategy: StrategyCandidate,
        metrics: BacktestMetrics,
        request: StrategyRequest,
    ) -> GovernanceDecision:
        reasons: list[str] = []
        blockers: list[str] = []
        required_approvals = list(self.config.get("human_in_loop", {}).get("roles", []))
        blocked_actions: list[ActionType] = []

        event = self.feature_registry.event(strategy.event_code)
        event_contract = self.feature_registry.build_event_contract(
            strategy.event_code
        )
        contract_errors = [
            issue.message
            for issue in event_contract.validation_issues
            if issue.severity == "error"
        ]
        blockers.extend(contract_errors)
        feature_errors = self.feature_registry.validate_decision_time(
            strategy.required_features, strategy.event_code
        )
        blockers.extend(feature_errors)

        if strategy.action not in event.allowed_actions:
            blockers.append(
                f"action {strategy.action.value} is not allowed for event {strategy.event_code}"
            )

        gates = self.config.get("simulation_gates", {})
        request_precision = max(float(gates.get("minimum_precision", 0.0)), request.minimum_precision)
        request_recall = max(float(gates.get("minimum_recall", 0.0)), request.minimum_recall)
        max_fpr = float(gates.get("maximum_false_positive_rate", 1.0))
        max_alert = min(float(gates.get("maximum_alert_rate", 1.0)), request.max_alert_rate)
        min_sample = int(gates.get("minimum_sample_size", 1))

        checks = {
            "sample_size": metrics.sample_size >= min_sample,
            "precision": metrics.precision >= request_precision,
            "recall": metrics.recall >= request_recall,
            "false_positive_rate": metrics.false_positive_rate <= max_fpr,
            "alert_rate": metrics.alert_rate <= max_alert,
        }
        for name, passed in checks.items():
            value = getattr(metrics, name)
            if passed:
                reasons.append(f"simulation gate passed: {name}={value:.4f}" if isinstance(value, float) else f"simulation gate passed: {name}={value}")
            else:
                blockers.append(f"simulation gate failed: {name}={value}")

        human_cfg = self.config.get("human_in_loop", {})
        restricted_values = set(human_cfg.get("restricted_actions", []))
        if strategy.action.value in restricted_values:
            blocked_actions.append(strategy.action)
            if "compliance" not in required_approvals:
                required_approvals.append("compliance")
            reasons.append("high-impact disposition requires compliance approval")

        if strategy.action in {ActionType.RFI, ActionType.EDD, ActionType.ESCALATE_COMPLIANCE}:
            if "compliance" not in required_approvals:
                required_approvals.append("compliance")

        if strategy.action in {
            ActionType.FREEZE,
            ActionType.REJECT,
            ActionType.WITHDRAWAL_RESTRICTION,
            ActionType.TRANSACTION_RESTRICTION,
        }:
            if "risk_owner" not in required_approvals:
                required_approvals.append("risk_owner")

        if request.require_human_review is False and (
            human_cfg.get("required", True) or strategy.action.value in restricted_values
        ):
            blockers.append("human review cannot be disabled for this strategy/action")

        current = StrategyStatus.SIMULATION
        if blockers:
            next_status = StrategyStatus.DRAFT
            decision = "revise"
            reasons.extend(blockers)
        else:
            next_status = StrategyStatus.PENDING_REVIEW
            decision = "approve"
            reasons.append("eligible to enter independent human review; not approved for production")

        if not self._transition_allowed(current, next_status):
            decision = "hold"
            reasons.append(f"invalid lifecycle transition: {current.value}->{next_status.value}")
            next_status = current

        audit_fields = {
            "request_id": request.request_id,
            "strategy_id": strategy.strategy_id,
            "event_code": strategy.event_code,
            "event_contract_version": event_contract.contract_version,
            "event_contract_hash": event_contract.contract_hash,
            "event_contract_warning_count": sum(
                issue.severity == "warning"
                for issue in event_contract.validation_issues
            ),
            "event_contract_error_count": len(contract_errors),
            "domain": strategy.domain.value,
            "action": strategy.action.value,
            "strategy_tags": {
                "level_1": strategy.tag_level_1,
                "level_2": strategy.tag_level_2,
                "level_3": strategy.tag_level_3,
                "flat": strategy.tags,
            },
            "rule_expression": rule_to_expression(strategy.rule),
            "required_features": strategy.required_features,
            "risk_source": "ai_assisted_candidate",
            "manual_override_policy": self.config.get("manual_override", {}),
            "str_confidentiality": self.config.get("confidentiality", {}),
            "reviewed_at": datetime.now(timezone.utc).isoformat(),
            "data_scope": "synthetic_or_aggregated_demo",
        }

        return GovernanceDecision(
            strategy_id=strategy.strategy_id,
            current_status=current,
            next_status=next_status,
            decision=decision,
            reasons=reasons,
            required_approvals=required_approvals,
            blocked_actions=blocked_actions,
            audit_fields=audit_fields,
        )

    def build_engine_payload(
        self,
        strategy: StrategyCandidate,
        governance: GovernanceDecision,
        metrics: BacktestMetrics,
    ) -> dict[str, Any]:
        """Build a rules-engine-shaped payload without authorizing production release."""
        return {
            "strategyId": strategy.strategy_id,
            "strategyName": strategy.name,
            "domain": strategy.domain.value,
            "eventCode": strategy.event_code,
            "strategyTags": {
                "level1": strategy.tag_level_1,
                "level2": strategy.tag_level_2,
                "level3": strategy.tag_level_3,
                "flat": strategy.tags,
            },
            "eventContract": {
                "version": governance.audit_fields["event_contract_version"],
                "sha256": governance.audit_fields["event_contract_hash"],
                "warningCount": governance.audit_fields[
                    "event_contract_warning_count"
                ],
                "errorCount": governance.audit_fields[
                    "event_contract_error_count"
                ],
            },
            "version": 1,
            "status": governance.next_status.value,
            "executionMode": "SIMULATION_ONLY",
            "conditionTree": engine_json(strategy.rule),
            "expression": rule_to_expression(strategy.rule),
            "action": {
                "type": strategy.action.value,
                "parameters": strategy.action_params,
                "requiresHumanApproval": True,
            },
            "guardrails": {
                "directOnlineRelease": False,
                "requiredApprovals": governance.required_approvals,
                "strDetailsVisibleInOrdinaryProfile": False,
                "manualRiskOverridePreserved": True,
                "kaVipExemptExtraApproval": True,
                "cmsOneClickCreatesInternalCaseOnly": True,
                "automaticRegulatorySubmission": False,
                "strategyEffectivenessTicketRequired": True,
            },
            "simulationSnapshot": {
                "selectionPartition": "development",
                "evaluationPartition": "out_of_time",
                "sampleSize": metrics.sample_size,
                "alerts": metrics.alerts,
                "precision": metrics.precision,
                "recall": metrics.recall,
                "f1": metrics.f1,
                "falsePositiveRate": metrics.false_positive_rate,
                "alertRate": metrics.alert_rate,
                "lift": metrics.lift,
                "capturedLossRate": metrics.captured_loss_rate,
                "stabilityScore": metrics.stability_score,
                "reward": metrics.reward,
                "relativeAdvantage": metrics.relative_advantage,
            },
            "audit": governance.audit_fields,
            "disclaimer": "Synthetic/desensitized prototype; payload is not connected to any production system.",
        }
