from __future__ import annotations

from .models import (
    DeliveryStage,
    EvidenceLevel,
    FeatureFamilyRecommendation,
    ModelAnalysisStep,
    ProblemLayer,
    SourceEvidence,
)


SOURCE_EVIDENCE: list[SourceEvidence] = [
    SourceEvidence(
        evidence_id="OCR-5716-PROBLEM-DECOMPOSITION",
        title="IMG_5716 macro-to-micro problem decomposition",
        evidence_level=EvidenceLevel.INTERNSHIP_DIRECT,
        source_type="ocr",
        scope="Macro objective -> regulatory/business requirement -> process -> data -> function/model -> solved problem",
        supports=["problem decomposition", "product thinking", "interview narration"],
        public_boundary="Only the abstracted method and sanitized evidence ID are public; raw screenshots and internal wording are excluded.",
    ),
    SourceEvidence(
        evidence_id="OCR-W27-KYC-PIT",
        title="KYC/VKYC field-availability and scoring-time conflict",
        evidence_level=EvidenceLevel.INTERNSHIP_DIRECT,
        source_type="ocr",
        scope="Known/unknown/contradiction/owner/evidence handling for a point-in-time data conflict",
        supports=["feature available_at", "point-in-time validation", "cross-team requirement clarification"],
        public_boundary="The repository uses a generic decision-time contract; no production field names, user records, or meeting recordings are included.",
    ),
    SourceEvidence(
        evidence_id="OCR-W26-DELIVERY-LIFECYCLE",
        title="Risk-product delivery lifecycle",
        evidence_level=EvidenceLevel.TEAM_SYSTEM,
        source_type="ocr",
        scope="Demand pool -> BRD -> PRD -> technical design -> schedule -> development -> integration test -> joint acceptance -> release -> RCA",
        supports=["delivery workflow", "owners", "exit gates", "rollback and evidence retention"],
        public_boundary="Only a provider-neutral workflow is reconstructed. Internal SLAs, names, and system identifiers are not published.",
    ),
    SourceEvidence(
        evidence_id="OCR-W28-FEATURE-LIFECYCLE",
        title="Feature platform and strategy backtracking capability",
        evidence_level=EvidenceLevel.TEAM_SYSTEM,
        source_type="ocr",
        scope="Real-time/offline/derived feature classification, definitions/use cases, long-window counters, 1:1 simulation, effectiveness metrics and lifecycle control",
        supports=["feature registry", "simulation", "strategy lifecycle", "effectiveness tickets"],
        public_boundary="The public profile contains synthetic ranges and generic semantics, not production thresholds or latency claims.",
    ),
    SourceEvidence(
        evidence_id="TXT-MAIN-SITE-AI-STRATEGY",
        title="Main-site AI strategy-assistant workflow notes",
        evidence_level=EvidenceLevel.TEAM_SYSTEM,
        source_type="txt",
        scope="Registered feature retrieval, candidate JSON, event permissions, human confirmation, simulation, approval, effect feedback and downgrade/offline logic",
        supports=["AI proposal guardrails", "structured strategy schema", "human-in-the-loop"],
        public_boundary="No raw TXT content is committed. The repository stores only a sanitized process abstraction.",
    ),
    SourceEvidence(
        evidence_id="OCR-W28-MODEL-ANALYSIS",
        title="Fraud feature, model and Risk Graph analysis materials",
        evidence_level=EvidenceLevel.TEAM_SYSTEM,
        source_type="ocr",
        scope="Label maturity, black/white sample comparison, feature families, AUC/KS/IV/Lift, Tree/XGBoost, graph paths, OOT, strategy overlap and operational feedback",
        supports=["model-analysis playbook", "feature effectiveness", "rule translation"],
        public_boundary="Team screenshots are not distributed. Prototype metrics are synthetic and cannot be represented as company performance.",
    ),
    SourceEvidence(
        evidence_id="OCR-W28-CASE-OPERATIONS",
        title="Anti-Fraud case-operation and quality metrics",
        evidence_level=EvidenceLevel.TEAM_SYSTEM,
        source_type="ocr",
        scope="Case ageing, backlog, status dwell time, evidence completeness, re-reply, reply quality and escalation",
        supports=["operational capacity", "case feedback labels", "post-launch monitoring"],
        public_boundary="The assistant uses generic capacity and quality gates. Internal targets and staff performance data are excluded.",
    ),
    SourceEvidence(
        evidence_id="GITHUB-CURRENT-COPILOT",
        title="Current synthetic Risk Strategy AI Copilot implementation",
        evidence_level=EvidenceLevel.PERSONAL_PROTOTYPE,
        source_type="github",
        scope="Feature registry/profiling, LR/Tree/XGBoost, Rule DSL, graph, temporal OOT, simulation, second review, effectiveness ticket and CMS/STR internal preview",
        supports=["implemented baseline", "deterministic controls", "synthetic-data validation"],
        public_boundary="This is a post-internship personal prototype and not a CoinTR production deployment.",
    ),
]


PROBLEM_LAYERS: list[ProblemLayer] = [
    ProblemLayer(
        order=1,
        layer="Macro objective",
        core_question="What company-level outcome makes this work necessary?",
        answer_template="The top-level objective is {business_objective}. Risk work is valuable only when it supports this operating objective rather than producing an isolated model score.",
        required_evidence=["business objective", "risk appetite", "licence/compliance or loss rationale"],
        output_object="Objective charter",
    ),
    ProblemLayer(
        order=2,
        layer="Regulatory or business requirement",
        core_question="Which concrete finding, loss mechanism, SLA or customer problem must be resolved?",
        answer_template="The broad objective is decomposed into a measurable requirement: {query}. The owner must define scope, target population, severity and acceptance criteria.",
        required_evidence=["finding or incident", "target metric", "owner", "deadline"],
        output_object="Requirement and acceptance criteria",
    ),
    ProblemLayer(
        order=3,
        layer="Business flow and state",
        core_question="Where does the risk occur in the end-to-end lifecycle and what is the irreversible control point?",
        answer_template="The risk is evaluated at event {event_code}. The analysis must reconstruct the states before and after that event, normal alternatives and the platform's intervention window.",
        required_evidence=["state machine", "event sequence", "normal path", "exception branches"],
        output_object="Business-flow and state diagram",
    ),
    ProblemLayer(
        order=4,
        layer="System, event and data",
        core_question="Which source is authoritative, which fields are available at decision time, and who owns them?",
        answer_template="Each signal requires a Feature Contract recording source, owner, window, freshness and available_at. A field produced after {event_code} cannot be used for that decision.",
        required_evidence=["source of truth", "event schema", "available_at", "data owner", "quality checks"],
        output_object="Event/Feature Contract and PIT audit",
    ),
    ProblemLayer(
        order=5,
        layer="Risk intelligence",
        core_question="What risk mechanism and evidence can rules, models and Risk Graph detect?",
        answer_template="Candidate evidence is organized into behaviour, funding, account-security, chain and relationship families; LR, Tree, XGBoost and graph analysis have different roles and are compared on mature Development labels.",
        required_evidence=["black-sample paths", "feature profiles", "model benchmarks", "graph paths"],
        output_object="Risk hypothesis and model-analysis pack",
    ),
    ProblemLayer(
        order=6,
        layer="Strategy, action and governance",
        core_question="How is analytical evidence converted into a controlled decision?",
        answer_template="A strategy object contains Event + Population + Feature/Window + Threshold + Exclusion + Action + Version + Evidence + Monitoring + Rollback. AI may propose; deterministic gates and human reviewers control status and action.",
        required_evidence=["Rule DSL", "action precedence", "simulation", "approvals", "rollback"],
        output_object="Versioned strategy-design object",
    ),
    ProblemLayer(
        order=7,
        layer="Validation, outcome and ownership",
        core_question="How will the team prove that the feature/model/strategy solved the original problem?",
        answer_template="Success is evaluated with OOT risk metrics, operational capacity, user/business impact and post-release feedback. The final owner records retain, tune, pause or retire decisions.",
        required_evidence=["OOT report", "effectiveness ticket", "case outcomes", "RCA", "owner decision"],
        output_object="Release/effectiveness decision and interview-ready narrative",
    ),
]


MODEL_ANALYSIS_PLAYBOOK: list[ModelAnalysisStep] = [
    ModelAnalysisStep(
        order=1,
        step="Define the business decision and action capacity",
        objective="Translate a broad risk concern into a decision that can be evaluated and operated.",
        required_checks=["decision event", "population and exclusions", "review capacity", "allowed actions", "false-positive burden"],
        metrics=["alert_rate", "review_capacity", "captured_loss", "operational_cost"],
        decision_standard=["A model metric without a decision/action objective is insufficient.", "Evaluation depth must match actual intervention capacity."],
        output="Decision charter and acceptance criteria",
        failure_action="Return to the business owner and revise the problem statement.",
    ),
    ModelAnalysisStep(
        order=2,
        step="Audit label source, maturity and selection bias",
        objective="Establish what the positive label means, when it becomes observable and which cases can receive a label.",
        required_checks=["label source", "maturity lag", "investigation-selection bias", "unlabelled != normal", "INCONCLUSIVE separate from negative"],
        metrics=["label_rate", "mature_label_rate", "investigation_selected_rate", "label_lag_days"],
        decision_standard=["Threshold discovery uses mature Development labels only.", "OOT labels stay hidden until the candidate is frozen."],
        output="Label contract and maturity view",
        failure_action="Hold development and repair the label or sampling plan.",
    ),
    ModelAnalysisStep(
        order=3,
        step="Reconstruct the full risk path",
        objective="Understand the ordered registration/KYC, login, funding, trading, transfer and withdrawal path before selecting features.",
        required_checks=["time-ordered sequence", "source/destination", "normal alternative explanations", "strong/weak relations", "intervention point"],
        metrics=["event_count", "time_to_next_event", "path_amount", "path_completion_rate"],
        decision_standard=["Each feature needs a plausible mechanism.", "One isolated signal is not a complete attack chain."],
        output="Risk path and feature-family map",
        failure_action="Perform black-sample case studies first.",
    ),
    ModelAnalysisStep(
        order=4,
        step="Validate data quality, lineage and decision-time availability",
        objective="Ensure every signal is reproducible at the target event.",
        required_checks=["source and owner", "window/freshness", "available_at <= decision_time", "coverage/duplicates/units", "downstream outcomes excluded"],
        metrics=["coverage", "missing_rate", "duplicate_rate", "freshness_lag", "PIT_violation_count"],
        decision_standard=["Any PIT violation blocks the feature.", "Missingness is retained only with documented meaning."],
        output="Feature Contract and leakage audit",
        failure_action="Reject or redesign the feature.",
    ),
    ModelAnalysisStep(
        order=5,
        step="Profile single-feature effectiveness and stability",
        objective="Measure separation, direction, coverage and drift before multivariate modelling.",
        required_checks=["bad/good distribution", "business direction", "Development-only metrics", "period stability", "segment stability"],
        metrics=["AUC", "KS", "IV/WOE", "Lift@capacity", "PSI", "missing_rate"],
        decision_standard=["IV evaluates a variable; KS evaluates overall separation; Lift evaluates the operating depth.", "No universal threshold replaces business and time stability."],
        output="Feature evidence cards",
        failure_action="Retire, segment or re-engineer unstable/low-value signals.",
    ),
    ModelAnalysisStep(
        order=6,
        step="Build a Logistic Regression baseline",
        objective="Create a linear, directionally interpretable and calibratable comparison anchor.",
        required_checks=["encoding fitted on Train", "coefficient direction", "multicollinearity", "calibration", "segment performance"],
        metrics=["ROC-AUC", "KS", "PR-AUC", "Brier/calibration", "Lift@capacity"],
        decision_standard=["Unexpected directions trigger data/segment review.", "LR is a baseline, not automatically the final strategy."],
        output="Linear baseline report",
        failure_action="Inspect encoding, leakage, segment mixing and interaction needs.",
    ),
    ModelAnalysisStep(
        order=7,
        step="Use a shallow Decision Tree for interactions and rule candidates",
        objective="Find explainable combinations and thresholds that can be translated into Rule DSL.",
        required_checks=["minimum leaf size", "leaf positive count", "risk ordering", "cross-period path stability", "business plausibility"],
        metrics=["leaf bad rate", "leaf lift", "coverage", "path stability", "tree depth"],
        decision_standard=["Tiny or risk-order-reversing leaves are rejected.", "Tree paths enter simulation; they are not automatically online rules."],
        output="Candidate paths and Rule DSL",
        failure_action="Prune, simplify or return to feature engineering.",
    ),
    ModelAnalysisStep(
        order=8,
        step="Train a nonlinear tabular model",
        objective="Combine nonlinearities and interactions after labels and features pass qualification.",
        required_checks=["Train-only sampling", "natural Development/OOT distribution", "regularisation", "feature importance stability", "calibration"],
        metrics=["ROC-AUC", "KS", "PR-AUC", "Lift@capacity", "recall", "FPR", "calibration"],
        decision_standard=["XGBoost is implemented; LightGBM is an optional efficiency benchmark, not a current repo claim.", "Model ordering is a Development decision; OOT is reporting-only."],
        output="Model benchmark and score evidence",
        failure_action="Prefer a simpler or more stable model when nonlinear gain is not operationally material.",
    ),
    ModelAnalysisStep(
        order=9,
        step="Add Risk Graph evidence",
        objective="Identify shared infrastructure and coordinated paths that account-level tabular models miss.",
        required_checks=["typed edges", "strong/weak relation policy", "one-hop/two-hop", "super-node suppression", "path explanation"],
        metrics=["seed precision", "incremental recall", "path coverage", "super-node rate", "community purity"],
        decision_standard=["Graph score alone is insufficient for high-impact action.", "IP and platform wallets are not standalone strong links."],
        output="Graph features and explainable paths",
        failure_action="Downgrade to monitor/manual review or repair graph policy.",
    ),
    ModelAnalysisStep(
        order=10,
        step="Evaluate chronological OOT and robustness",
        objective="Measure future-period performance and uncertainty without tuning on OOT.",
        required_checks=["chronological split", "OOT not reused", "period metrics", "bootstrap CI", "feature direction and PSI"],
        metrics=["period precision/recall", "alert-rate CV", "bootstrap CI", "PSI", "stability status"],
        decision_standard=["A candidate that degrades across time cannot pass only because pooled AUC is high.", "All threshold choices are frozen before OOT."],
        output="OOT and stability report",
        failure_action="Revise features, threshold, population or action.",
    ),
    ModelAnalysisStep(
        order=11,
        step="Translate model evidence into a strategy and test incremental value",
        objective="Convert rankings and paths into an auditable action while avoiding duplicate workload.",
        required_checks=["Event/Population/Window/Threshold/Exclusion/Action", "old/new overlap", "Swap-in/Swap-out", "incremental TP/recall", "action conflicts"],
        metrics=["Jaccard", "containment", "incremental recall", "duplicate workload", "Swap-in risk", "Swap-out risk"],
        decision_standard=["High standalone F1 does not justify a duplicate strategy.", "Action precedence conflicts require explicit review."],
        output="Versioned strategy-design object and conflict report",
        failure_action="Merge, revise or reject the candidate.",
    ),
    ModelAnalysisStep(
        order=12,
        step="Run simulation, independent review and release readiness",
        objective="Bind exact data, contracts, code and payload before any release decision.",
        required_checks=["data snapshot", "feature/event version", "payload hash", "1:1 simulation", "second reviewer", "rollback/monitoring"],
        metrics=["simulation precision/recall", "alert volume", "latency", "capacity", "rollback readiness"],
        decision_standard=["AI cannot change lifecycle status or execute punishment.", "High-impact actions require additional approval."],
        output="Simulation and independent-review package",
        failure_action="Return to backtest, design or data stages.",
    ),
    ModelAnalysisStep(
        order=13,
        step="Close the post-release effectiveness loop",
        objective="Use operational outcomes to decide retain, tune, pause or retire.",
        required_checks=["confirmed outcome", "case ageing", "evidence quality", "appeal/complaint", "feature drift", "action result"],
        metrics=["confirmed-positive rate", "case SLA", "re-reply rate", "complaint rate", "PSI", "net loss"],
        decision_standard=["Feedback labels are governed and can remain inconclusive.", "A degraded strategy is paused or revised rather than silently retained."],
        output="Effectiveness ticket and lifecycle decision",
        failure_action="Trigger RCA and a new controlled iteration.",
    ),
]


DELIVERY_WORKFLOW: list[DeliveryStage] = [
    DeliveryStage(order=1, stage="Demand intake and demand-pool registration", owner="requestor", collaborators=["risk_product"], required_inputs=["background", "scenario", "risk impact", "functional objective", "priority"], required_outputs=["standard demand record", "initial acceptance criteria"], exit_gate=["scope and owner are clear", "parameter-only change separated from product demand"]),
    DeliveryStage(order=2, stage="BRD preparation and multi-round review", owner="risk_product", collaborators=["requestor", "local_business_or_compliance"], required_inputs=["demand record", "current process", "known/unknown/contradiction list"], required_outputs=["BRD", "process/state map", "field and permission gaps"], exit_gate=["normal and exception branches covered", "no oral-only requirement change"], rollback_to="Demand intake and demand-pool registration"),
    DeliveryStage(order=3, stage="PRD and detailed review", owner="risk_product", collaborators=["engineering", "QA", "requestor"], required_inputs=["approved BRD", "event/feature contract"], required_outputs=["PRD", "UI/API/state rules", "acceptance cases"], exit_gate=["all branches and permissions specified", "requestor confirms business meaning"], rollback_to="BRD preparation and multi-round review"),
    DeliveryStage(order=4, stage="Technical design and review", owner="engineering_lead", collaborators=["risk_product", "QA", "data_or_algorithm"], required_inputs=["approved PRD", "non-functional constraints"], required_outputs=["technical design", "data lineage", "dependency and rollback plan"], exit_gate=["technical design matches PRD", "PIT, audit and security risks addressed"], rollback_to="PRD and detailed review"),
    DeliveryStage(order=5, stage="Engineering schedule and admission", owner="engineering_lead", collaborators=["risk_product"], required_inputs=["approved design", "dependency estimate"], required_outputs=["milestones", "owners", "risk register", "release target"], exit_gate=["schedule and dependencies accepted", "blockers have escalation owners"], rollback_to="Technical design and review"),
    DeliveryStage(order=6, stage="Development and unit testing", owner="engineering", collaborators=["risk_product"], required_inputs=["approved design", "testable contracts"], required_outputs=["implementation", "unit tests", "change log"], exit_gate=["unit and contract tests pass", "logic changes are versioned"], rollback_to="Engineering schedule and admission"),
    DeliveryStage(order=7, stage="Integration testing", owner="QA", collaborators=["engineering", "risk_product"], required_inputs=["deployable build", "integration cases"], required_outputs=["integration report", "bug list and fixes"], exit_gate=["functional and boundary cases pass", "blocking bugs closed"], rollback_to="Development and unit testing"),
    DeliveryStage(order=8, stage="Joint test-environment acceptance", owner="risk_product_and_requestor", collaborators=["QA", "engineering"], required_inputs=["integration report", "acceptance checklist"], required_outputs=["signed acceptance record", "remaining non-blocking items"], exit_gate=["two-sided acceptance completed", "evidence retained"], rollback_to="Integration testing"),
    DeliveryStage(order=9, stage="Joint production-environment acceptance", owner="risk_product_and_requestor", collaborators=["operations", "engineering"], required_inputs=["release candidate", "production acceptance plan"], required_outputs=["production acceptance evidence", "go/no-go decision"], exit_gate=["production acceptance completed", "no team silently waives acceptance"], rollback_to="Integration testing"),
    DeliveryStage(order=10, stage="Formal release", owner="operations_or_engineering", collaborators=["all_participating_teams"], required_inputs=["all approvals", "release package"], required_outputs=["release record", "exact version/payload hash", "monitoring ticket"], exit_gate=["approved release window", "rollback remains available"], rollback_to="Joint production-environment acceptance"),
    DeliveryStage(order=11, stage="Post-release RCA and iteration", owner="risk_product", collaborators=["requestor", "engineering", "QA", "operations", "risk_strategy"], required_inputs=["monitoring data", "defects", "business/risk outcomes"], required_outputs=["RCA", "corrective actions", "effectiveness decision", "next iteration"], exit_gate=["root cause recorded", "retain/tune/pause/retire decision made"], rollback_to="Demand intake and demand-pool registration"),
]


FEATURE_FAMILY_CATALOG: dict[str, list[FeatureFamilyRecommendation]] = {
    "account_takeover": [
        FeatureFamilyRecommendation(family="authentication_and_security_change", business_hypothesis="ATO often combines credential abuse, failed authentication and sensitive-security changes before withdrawal.", candidate_features=["failed_login_count_1h", "new_device_flag", "recent_password_change_flag", "phone_change_7d_flag", "email_change_7d_flag", "geo_velocity_kmh"], aggregation_or_transformation=["1h/24h velocity", "security-change sequence", "new-device plus beneficiary interaction"], model_role="High-recall behaviour signals combined with transaction or relationship evidence.", false_positive_controls=["trusted-device history", "travel pattern", "support-assisted reset", "managed-account review"]),
        FeatureFamilyRecommendation(family="withdrawal_and_relationship_evidence", business_hypothesis="Compromised accounts often add a new destination and withdraw shortly after the security event.", candidate_features=["new_withdraw_address_flag", "minutes_deposit_to_first_chain_out", "chain_out_5min_count_30d", "strong_relation_fraud_1hop_count", "fraud_graph_score"], aggregation_or_transformation=["minutes since security change", "new beneficiary", "one-hop strong-edge count", "path evidence"], model_role="Precision enhancement and action routing.", false_positive_controls=["known beneficiary", "customer tenure", "verified KYC", "super-node suppression"]),
    ],
    "rapid_cashout": [
        FeatureFamilyRecommendation(family="fund_velocity_and_closed_loop", business_hypothesis="Rapid fiat-in, conversion and chain-out with little economic trading purpose can indicate cash-out or layering.", candidate_features=["fiat_in_crypto_out_ratio", "minutes_fiat_in_to_convert", "minutes_convert_to_chain_out", "fund_stay_minutes_median", "strategy_avoidance_ratio_30d"], aggregation_or_transformation=["event-sequence duration", "in/out ratio", "recent-versus-lifetime velocity", "path completion"], model_role="Primary mechanism for rules and nonlinear models.", false_positive_controls=["market-maker/treasury activity", "known recurring pattern", "same-owner transfer", "customer segment"]),
        FeatureFamilyRecommendation(family="bank_chain_and_graph_evidence", business_hypothesis="Risky funding instruments, chain exposure and shared exit wallets strengthen the fund-flow case.", candidate_features=["unique_deposit_bankcards_30d", "bank_name_mismatch_flag", "bank_fraud_ratio_max", "high_risk_chain_exposure", "mixer_exposure", "strong_relation_fraud_1hop_count"], aggregation_or_transformation=["unique count", "risk weighted exposure", "shared destination fan-in", "explainable graph path"], model_role="Secondary evidence and RFI/EDD action routing.", false_positive_controls=["corporate account", "tag confidence", "amount materiality", "business rationale"]),
    ],
    "aml_layering": [
        FeatureFamilyRecommendation(family="internal_transfer_and_source_of_funds", business_hypothesis="Fan-in, fan-out and layered transfers can obscure origin before external withdrawal.", candidate_features=["internal_transfer_amount_24h", "internal_transfer_count_24h", "fan_in_degree_24h", "fan_out_degree_24h", "counterparty_fraud_ratio", "source_of_funds_risk"], aggregation_or_transformation=["directed path length", "net-flow conservation", "counterparty concentration", "community features"], model_role="Graph/path detection and compliance evidence bundle.", false_positive_controls=["merchant settlement", "family/corporate group", "treasury", "operational account"]),
    ],
    "campaign_abuse": [
        FeatureFamilyRecommendation(family="device_identity_inviter_cluster", business_hypothesis="Campaign abuse often uses repeated identity/device/email patterns and clustered inviter or reward destinations.", candidate_features=["device_user_count_24h", "email_similarity_cluster_size", "kyc_document_similarity_count", "inviter_cluster_size", "reward_address_cluster_size", "campaign_task_similarity"], aggregation_or_transformation=["cluster size", "sequence similarity", "reward-address concentration", "identity reuse"], model_role="High-recall graph/behaviour detection followed by campaign-specific action.", false_positive_controls=["shared household/device", "agency or employee account", "test account", "campaign rules"]),
    ],
    "market_abuse": [
        FeatureFamilyRecommendation(family="trade_order_and_control_relationship", business_hypothesis="Wash trading, spoofing and coordinated manipulation require joint analysis of orders, executions, cancellations and control relationships.", candidate_features=["wash_trade_similarity", "cancel_ratio_1h", "api_activity_ratio_30d", "night_activity_ratio_30d", "counterparty_fraud_ratio"], aggregation_or_transformation=["self/circular trade ratio", "near-time/price/size similarity", "order-to-trade ratio", "PnL transfer", "event-window analysis"], model_role="Scenario-specific rules plus graph and sequence analytics.", false_positive_controls=["approved market-making mandate", "liquidity regime", "hedging", "exchange-wide volatility"]),
    ],
}


DEFAULT_FEATURE_FAMILIES = FEATURE_FAMILY_CATALOG["rapid_cashout"]
